### ISSUE TITLE
NeoForge 1.20.2 Crashing

### ISSUE THREAD

**Issue by MarkusBordihn** [MarkusBordihn/BOs-Trank-O-Mat#2]
```
	Caused by 0: java.lang.NoClassDefFoundError: net/neoforged/neoforge/registries/ForgeRegistries
		at de.markusbordihn.trankomat.block.ModBlocks.<clinit>(ModBlocks.java:30) ~[Trank-O-Mat-neoforge-1.20.2-1.1.2.jar%23182!/:1.1.2] {re:classloading}
		at de.markusbordihn.trankomat.TrankOMat.<init>(TrankOMat.java:45) ~[Trank-O-Mat-neoforge-1.20.2-1.1.2.jar%23182!/:1.1.2] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:112) ~[language-java-1.0.16.jar%23185!/:1.0] {}
		at net.neoforged.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:130) ~[core-1.0.16.jar%23184!/:1.0] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /G:/Minecraft/CurseForge/Instances/My Mods 1.20.2 (NeoForge)/mods/Trank-O-Mat-neoforge-1.20.2-1.1.2.jar
	Failure message: Trank-O-Mat (trank_o_mat) has failed to load correctly
		java.lang.NoClassDefFoundError: net/neoforged/neoforge/registries/ForgeRegistries
	Mod Version: 1.1.2
	Mod Issue URL: https://github.com/MarkusBordihn/BOs-Trank-O-Mat/issues
	Exception message: java.lang.ClassNotFoundException: net.neoforged.neoforge.registries.ForgeRegistries
```

**Comment by MarkusBordihn** [comment]
Related to: https://neoforged.net/news/20.2registry-rework/
